### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: io.swagger.models.parameters.AbstractSerializableParameter.getDefaultValue()Ljava/lang/String;

### ISSUE THREAD

**Issue by zcb22000** [swagger-api/swagger-core#2095]
swagger-core version 2.2.2-SNAPSHOT (master)
swagger-models version 1.5.12
When i generate apis, it throw exception:
`
Exception in thread "main" java.lang.NoSuchMethodError: io.swagger.models.parameters.AbstractSerializableParameter.getDefaultValue()Ljava/lang/String;
	at io.github.swagger2markup.internal.adapter.ParameterAdapter.getDefaultValue(ParameterAdapter.java:200)
	at io.github.swagger2markup.internal.adapter.ParameterAdapter.displayDefaultValue(ParameterAdapter.java:109)
	at io.github.swagger2markup.internal.component.ParameterTableComponent.apply(ParameterTableComponent.java:100)
	at io.github.swagger2markup.internal.component.PathOperationComponent.buildParametersSection(PathOperationComponent.java:198)
	at io.github.swagger2markup.internal.component.PathOperationComponent.apply(PathOperationComponent.java:100)
	at io.github.swagger2markup.internal.document.PathsDocument.applyPathOperationComponent(PathsDocument.java:223)
	at io.github.swagger2markup.internal.document.PathsDocument.buildOperation(PathsDocument.java:207)
	at io.github.swagger2markup.internal.document.PathsDocument.lambda$null$1(PathsDocument.java:133)
	at io.github.swagger2markup.internal.document.PathsDocument$$Lambda$25/308889081.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at io.github.swagger2markup.internal.document.PathsDocument.lambda$buildsPathsSection$2(PathsDocument.java:133)
	at io.github.swagger2markup.internal.document.PathsDocument$$Lambda$24/608519258.accept(Unknown Source)
	at java.util.TreeMap.forEach(TreeMap.java:1001)
	at io.github.swagger2markup.internal.document.PathsDocument.buildsPathsSection(PathsDocument.java:127)
	at io.github.swagger2markup.internal.document.PathsDocument.apply(PathsDocument.java:103)
	at io.github.swagger2markup.Swagger2MarkupConverter.applyPathsDocument(Swagger2MarkupConverter.java:197)
	at io.github.swagger2markup.Swagger2MarkupConverter.toFolder(Swagger2MarkupConverter.java:182)

`

**Comment by fehguy** [comment]
Looks from your trace like this is a swagger2markup issue.  And there's no 2.2.2-SNAPSHOT of swagger-core

**Comment by phirzel** [comment]
I also get an Exception if use springfox-swagger2 **v2.8.0** (with **2.7.0 it is ok!**). I assume there is a nasty BUG in 2.8.0:
Caused by: java.lang.NoSuchMethodError: io.swagger.annotations.ApiParam.collectionFormat()Ljava/lang/String;
	at springfox.documentation.swagger.readers.parameter.ApiParamParameterBuilder.apply(ApiParamParameterBuilder.java:66)
	at springfox.documentation.spring.web.plugins.DocumentationPluginsManager.parameter(DocumentationPluginsManager.java:106)
	at springfox.documentation.spring.web.readers.operation.OperationParameterReader.readParameters(OperationParameterReader.java:103)
	at springfox.documentation.spring.web.readers.operation.OperationParameterReader.apply(OperationParameterReader.java:75)
	at springfox.documentation.spring.web.plugins.DocumentationPluginsManager.operation(DocumentationPluginsManager.java:120)
	at springfox.documentation.spring.web.readers.operation.ApiOperationReader.read(ApiOperationReader.java:73)
	at springfox.documentation.spring.web.scanners.CachingOperationReader$1.load(CachingOperationReader.java:50)
	at springfox.documentation.spring.web.scanners.CachingOperationReader$1.load(CachingOperationReader.java:48)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)

**Comment by JesonMars** [comment]
I also get an Exception used version2.6.1,I think it's a swagger bug, and after upgrade to v2.7.0 then sloved this Exception
